version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: primetrade-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - primetrade-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: primetrade-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/primetrade_tasks
      - JWT_SECRET=primetrade_super_secret_key_change_in_prod
      - JWT_EXPIRES_IN=7d
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - primetrade-net
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  primetrade-net:
    driver: bridge
